(package "undohist"
         "0.2.1"
         "Persistent undo history for GNU Emacs")

(website-url "https://github.com/emacsorphanage/undohist")
(keywords "convenience")

(package-file "undohist.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
